import { translated, type ObjectNameKey } from '../i18n';

/** Short object-tree labels shared by repeated OpenAPI fields. */
const labels: Readonly<Record<string, readonly [en: ObjectNameKey, de: string]>> = {
	activeVentilation: ['Active ventilation', 'Aktive Belüftung'],
	airConditioning: ['Air conditioning', 'Klimatisierung'],
	auxiliaryHeating: ['Auxiliary heating', 'Standheizung'],
	charging: ['Charging', 'Laden'],
	chargingProfiles: ['Charging profiles', 'Ladeprofile'],
	currentVehiclePositionProfile: ['Current location profile', 'Profil am aktuellen Standort'],
	fuelStatus: ['Fuel status', 'Kraftstoffstatus'],
	primaryEngineRange: ['Primary engine range', 'Reichweite des Hauptantriebs'],
	secondaryEngineRange: ['Secondary engine range', 'Reichweite des Nebenantriebs'],
	odometer: ['Odometer', 'Kilometerstand'],
	parkingPosition: ['Parking position', 'Parkposition'],
	gpsCoordinates: ['GPS coordinates', 'GPS-Koordinaten'],
	status: ['Vehicle status', 'Fahrzeugstatus'],
	detail: ['Detailed status', 'Detailstatus'],
	overall: ['Overall status', 'Gesamtstatus'],
	settings: ['Settings', 'Einstellungen'],
	targetTemperature: ['Target temperature', 'Zieltemperatur'],
	windowHeating: ['Window heating', 'Scheibenheizung'],
	battery: ['Battery', 'Batterie'],
	carCapturedTimestamp: ['Vehicle data timestamp', 'Zeitstempel der Fahrzeugdaten'],
	durationInSeconds: ['Duration', 'Dauer'],
	state: ['State', 'Status'],
	airConditioningAtUnlock: ['Air conditioning on unlock', 'Klimatisierung beim Entriegeln'],
	airConditioningWithoutExternalPower: [
		'Air conditioning without external power',
		'Klimatisierung ohne externe Stromversorgung',
	],
	estimatedReachOfTargetTemperatureAt: ['Target temperature reached at', 'Zieltemperatur erreicht um'],
	unit: ['Unit', 'Einheit'],
	value: ['Value', 'Wert'],
	enabled: ['Enabled', 'Aktiviert'],
	front: ['Front', 'Vorne'],
	rear: ['Rear', 'Hinten'],
	startMode: ['Start mode', 'Startmodus'],
	isVehicleInSavedLocation: ['Vehicle in saved location', 'Fahrzeug an gespeichertem Standort'],
	autoUnlockPlugWhenCharged: ['Unlock plug after charging', 'Ladestecker nach dem Laden entriegeln'],
	availableChargeModes: ['Available charging modes', 'Verfügbare Lademodi'],
	batteryCareModeTargetValueInPercent: ['Battery care target level', 'Zielladestand der Batteriepflege'],
	chargingCareMode: ['Battery care mode', 'Batteriepflegemodus'],
	maxChargeCurrentAc: ['Maximum AC charging current', 'Maximaler AC-Ladestrom'],
	maxChargeCurrentAcAmpere: ['Maximum AC charging current', 'Maximaler AC-Ladestrom'],
	preferredChargeMode: ['Preferred charging mode', 'Bevorzugter Lademodus'],
	targetStateOfChargeInPercent: ['Target state of charge', 'Zielladestand'],
	remainingCruisingRangeInMeters: ['Remaining electric range', 'Verbleibende elektrische Reichweite'],
	stateOfChargeInPercent: ['State of charge', 'Ladestand'],
	chargePowerInKw: ['Charging power', 'Ladeleistung'],
	chargeType: ['Charging type', 'Ladeart'],
	chargingRateInKilometersPerHour: ['Charging rate', 'Ladegeschwindigkeit'],
	fullyChargedAt: ['Fully charged at', 'Vollständig geladen um'],
	remainingTimeToFullyChargedInMinutes: ['Remaining charging time', 'Verbleibende Ladezeit'],
	id: ['Identifier', 'Kennung'],
	name: ['Name', 'Name'],
	nextChargingTime: ['Next charging time', 'Nächste Ladezeit'],
	profiles: ['Profiles', 'Profile'],
	adBlueRange: ['AdBlue range', 'AdBlue-Reichweite'],
	carType: ['Vehicle type', 'Fahrzeugtyp'],
	currentFuelLevelInPercent: ['Fuel level', 'Kraftstoffstand'],
	currentSoCInPercent: ['State of charge', 'Ladestand'],
	engineType: ['Engine type', 'Antriebsart'],
	remainingRangeInKm: ['Remaining range', 'Verbleibende Reichweite'],
	totalRangeInKm: ['Total range', 'Gesamtreichweite'],
	licensePlate: ['License plate', 'Kennzeichen'],
	mileageInKm: ['Mileage', 'Kilometerstand'],
	operations: ['Supported remote operations', 'Unterstützte Fernzugriffe'],
	formattedAddress: ['Address', 'Adresse'],
	latitude: ['Latitude', 'Breitengrad'],
	longitude: ['Longitude', 'Längengrad'],
	renderUrl: ['Vehicle image URL', 'URL des Fahrzeugbilds'],
	bonnet: ['Bonnet', 'Motorhaube'],
	sunroof: ['Sunroof', 'Schiebedach'],
	trunk: ['Trunk', 'Kofferraum'],
	doors: ['Doors', 'Türen'],
	doorsLocked: ['Door lock state', 'Verriegelungsstatus der Türen'],
	lights: ['Lights', 'Lichter'],
	locked: ['Lock state', 'Verriegelungsstatus'],
	reliableLockStatus: ['Reliable lock status', 'Verlässlicher Verriegelungsstatus'],
	windows: ['Windows', 'Fenster'],
	vin: ['Vehicle identification number', 'Fahrgestellnummer'],
};

/**
 * Returns a complete translated label and retains the OpenAPI text as a string fallback.
 *
 * @param path Relativer Pfad des Objekts.
 * @param fallback Englischer Text aus der OpenAPI-Spezifikation.
 */
export function localizedObjectName(path: string, fallback: string): ioBroker.StringOrTranslated {
	const label = labels[path.slice(path.lastIndexOf('.') + 1)];
	return label ? translated(label[0], label[1]) : fallback;
}
